# Python & Shell Workflow Aliases
# Auto-generated by python-shell-optimizer.sh

# ============================================================================
# Python Shortcuts (48% of your activity)
# ============================================================================

# Quick Python operations
alias py='python3'
alias py-test='python3 -m pytest'
alias py-venv='python3 -m venv venv && source venv/bin/activate'
alias py-install='pip install -r requirements.txt'
alias py-freeze='pip freeze > requirements.txt'
alias py-lint='python3 -m flake8'
alias py-format='python3 -m black'
alias py-type='python3 -m mypy'

# Python debugging
alias py-debug='python3 -m pdb'
alias py-profile='python3 -m cProfile -s cumulative'
alias py-trace='python3 -m trace --trace'

# Python environment
alias py-which='which python3 && python3 --version'
alias py-path='python3 -c "import sys; print(\"\n\".join(sys.path))"'
alias py-site='python3 -m site'

# Python quick checks
py-check() {
  echo "🐍 Python Environment Check"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Version: $(python3 --version)"
  echo "Location: $(which python3)"
  echo "Pip: $(pip --version 2>/dev/null || echo 'not found')"
  echo "Virtual Env: ${VIRTUAL_ENV:-none}"
  echo ""
  echo "Installed packages:"
  pip list 2>/dev/null | head -10 || echo "No packages"
}

# Python quick script runner
py-run() {
  local script="$1"
  shift
  if [[ -f "$script" ]]; then
    python3 "$script" "$@"
  else
    # Treat as inline code
    python3 -c "$script" "$@"
  fi
}

# Python dependency analyzer
py-deps() {
  echo "📦 Analyzing Python dependencies..."
  if [[ -f "requirements.txt" ]]; then
    echo "requirements.txt found ($(wc -l < requirements.txt) packages)"
    grep -v "^#" requirements.txt | head -10
  fi
  if [[ -f "setup.py" ]]; then
    echo "setup.py found"
  fi
  if [[ -f "pyproject.toml" ]]; then
    echo "pyproject.toml found"
  fi
}

# ============================================================================
# Shell Shortcuts (47% of your activity)
# ============================================================================

# Quick file operations
alias ll='ls -lahF'
alias la='ls -A'
alias l='ls -CF'
alias tree='find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"'

# Quick search
alias ff='find . -name'
alias gg='grep -rn'
alias hh='history | grep'

# System info
alias cpu='top -l 1 | grep "CPU usage"'
alias mem='top -l 1 | grep PhysMem'
alias disk='df -h'
alias ports='lsof -i -P | grep LISTEN'

# Process management
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias kill-port='function _kp(){ lsof -ti:$1 | xargs kill -9; }; _kp'

# Quick directory navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Safety aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Quick git (for shell scripts in git repos)
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -10'
alias gp='git pull'

# Shell script helpers
sh-check() {
  local script="${1:-.}"
  echo "🔍 Checking shell scripts..."
  if command -v shellcheck >/dev/null 2>&1; then
    find "$script" -name "*.sh" -type f -exec shellcheck {} \;
  else
    echo "⚠️  shellcheck not installed (brew install shellcheck)"
  fi
}

sh-format() {
  local script="${1:-.}"
  echo "✨ Formatting shell scripts..."
  if command -v shfmt >/dev/null 2>&1; then
    find "$script" -name "*.sh" -type f -exec shfmt -w -i 2 {} \;
  else
    echo "⚠️  shfmt not installed (brew install shfmt)"
  fi
}

sh-profile() {
  local script="$1"
  echo "⏱️  Profiling shell script: $script"
  time bash -x "$script" 2>&1 | tail -20
}

# ============================================================================
# Combined Python + Shell Workflows
# ============================================================================

# Quick project setup
project-init() {
  local name="${1:-project}"
  echo "🚀 Initializing Python/Shell project: $name"

  mkdir -p "$name"/{src,tests,scripts,docs}

  # Python files
  touch "$name/requirements.txt"
  touch "$name/setup.py"
  touch "$name/README.md"
  touch "$name/.gitignore"

  # Shell scripts
  cat > "$name/scripts/setup.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
echo "Setting up project..."
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
echo "✓ Setup complete"
SCRIPT

  chmod +x "$name/scripts/setup.sh"

  echo "✓ Project structure created: $name"
  tree "$name" 2>/dev/null || ls -R "$name"
}

# Quick test runner (Python + Shell)
run-all-tests() {
  echo "🧪 Running all tests..."

  # Python tests
  if [[ -d "tests" ]] && find tests -name "test_*.py" -o -name "*_test.py" | grep -q .; then
    echo "Running Python tests..."
    python3 -m pytest tests/ -v
  fi

  # Shell script tests
  if [[ -d "tests" ]] && find tests -name "test_*.sh" -o -name "*_test.sh" | grep -q .; then
    echo "Running Shell tests..."
    for test in tests/test_*.sh tests/*_test.sh; do
      [[ -f "$test" ]] && bash "$test"
    done
  fi
}

# Quick lint everything
lint-all() {
  echo "🔍 Linting all code..."

  # Python
  if find . -name "*.py" | grep -q .; then
    echo "Linting Python files..."
    python3 -m flake8 . 2>/dev/null || echo "⚠️  flake8 not installed"
  fi

  # Shell
  if find . -name "*.sh" | grep -q .; then
    echo "Linting Shell scripts..."
    sh-check .
  fi
}

# Quick format everything
format-all() {
  echo "✨ Formatting all code..."

  # Python
  if find . -name "*.py" | grep -q .; then
    echo "Formatting Python files..."
    python3 -m black . 2>/dev/null || echo "⚠️  black not installed"
  fi

  # Shell
  if find . -name "*.sh" | grep -q .; then
    echo "Formatting Shell scripts..."
    sh-format .
  fi
}

