#!/usr/bin/env bash
# python-shell-optimizer.sh - Workflow optimizations for Python/Shell
# Tailored for your 96% Python/Shell usage pattern

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RESET='\033[0m'

ALIASES_FILE="$HOME/.claude/aliases/python-shell.sh"
TEMPLATES_DIR="$HOME/.claude/templates"

# Create optimized aliases
create_aliases() {
  mkdir -p "$(dirname "$ALIASES_FILE")"

  cat > "$ALIASES_FILE" << 'EOF'
# Python & Shell Workflow Aliases
# Auto-generated by python-shell-optimizer.sh

# ============================================================================
# Python Shortcuts (48% of your activity)
# ============================================================================

# Quick Python operations
alias py='python3'
alias py-test='python3 -m pytest'
alias py-venv='python3 -m venv venv && source venv/bin/activate'
alias py-install='pip install -r requirements.txt'
alias py-freeze='pip freeze > requirements.txt'
alias py-lint='python3 -m flake8'
alias py-format='python3 -m black'
alias py-type='python3 -m mypy'

# Python debugging
alias py-debug='python3 -m pdb'
alias py-profile='python3 -m cProfile -s cumulative'
alias py-trace='python3 -m trace --trace'

# Python environment
alias py-which='which python3 && python3 --version'
alias py-path='python3 -c "import sys; print(\"\n\".join(sys.path))"'
alias py-site='python3 -m site'

# Python quick checks
py-check() {
  echo "🐍 Python Environment Check"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Version: $(python3 --version)"
  echo "Location: $(which python3)"
  echo "Pip: $(pip --version 2>/dev/null || echo 'not found')"
  echo "Virtual Env: ${VIRTUAL_ENV:-none}"
  echo ""
  echo "Installed packages:"
  pip list 2>/dev/null | head -10 || echo "No packages"
}

# Python quick script runner
py-run() {
  local script="$1"
  shift
  if [[ -f "$script" ]]; then
    python3 "$script" "$@"
  else
    # Treat as inline code
    python3 -c "$script" "$@"
  fi
}

# Python dependency analyzer
py-deps() {
  echo "📦 Analyzing Python dependencies..."
  if [[ -f "requirements.txt" ]]; then
    echo "requirements.txt found ($(wc -l < requirements.txt) packages)"
    grep -v "^#" requirements.txt | head -10
  fi
  if [[ -f "setup.py" ]]; then
    echo "setup.py found"
  fi
  if [[ -f "pyproject.toml" ]]; then
    echo "pyproject.toml found"
  fi
}

# ============================================================================
# Shell Shortcuts (47% of your activity)
# ============================================================================

# Quick file operations
alias ll='ls -lahF'
alias la='ls -A'
alias l='ls -CF'
alias tree='find . -print | sed -e "s;[^/]*/;|____;g;s;____|; |;g"'

# Quick search
alias ff='find . -name'
alias gg='grep -rn'
alias hh='history | grep'

# System info
alias cpu='top -l 1 | grep "CPU usage"'
alias mem='top -l 1 | grep PhysMem'
alias disk='df -h'
alias ports='lsof -i -P | grep LISTEN'

# Process management
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias kill-port='function _kp(){ lsof -ti:$1 | xargs kill -9; }; _kp'

# Quick directory navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Safety aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Quick git (for shell scripts in git repos)
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -10'
alias gp='git pull'

# Shell script helpers
sh-check() {
  local script="${1:-.}"
  echo "🔍 Checking shell scripts..."
  if command -v shellcheck >/dev/null 2>&1; then
    find "$script" -name "*.sh" -type f -exec shellcheck {} \;
  else
    echo "⚠️  shellcheck not installed (brew install shellcheck)"
  fi
}

sh-format() {
  local script="${1:-.}"
  echo "✨ Formatting shell scripts..."
  if command -v shfmt >/dev/null 2>&1; then
    find "$script" -name "*.sh" -type f -exec shfmt -w -i 2 {} \;
  else
    echo "⚠️  shfmt not installed (brew install shfmt)"
  fi
}

sh-profile() {
  local script="$1"
  echo "⏱️  Profiling shell script: $script"
  time bash -x "$script" 2>&1 | tail -20
}

# ============================================================================
# Combined Python + Shell Workflows
# ============================================================================

# Quick project setup
project-init() {
  local name="${1:-project}"
  echo "🚀 Initializing Python/Shell project: $name"

  mkdir -p "$name"/{src,tests,scripts,docs}

  # Python files
  touch "$name/requirements.txt"
  touch "$name/setup.py"
  touch "$name/README.md"
  touch "$name/.gitignore"

  # Shell scripts
  cat > "$name/scripts/setup.sh" << 'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
echo "Setting up project..."
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
echo "✓ Setup complete"
SCRIPT

  chmod +x "$name/scripts/setup.sh"

  echo "✓ Project structure created: $name"
  tree "$name" 2>/dev/null || ls -R "$name"
}

# Quick test runner (Python + Shell)
run-all-tests() {
  echo "🧪 Running all tests..."

  # Python tests
  if [[ -d "tests" ]] && find tests -name "test_*.py" -o -name "*_test.py" | grep -q .; then
    echo "Running Python tests..."
    python3 -m pytest tests/ -v
  fi

  # Shell script tests
  if [[ -d "tests" ]] && find tests -name "test_*.sh" -o -name "*_test.sh" | grep -q .; then
    echo "Running Shell tests..."
    for test in tests/test_*.sh tests/*_test.sh; do
      [[ -f "$test" ]] && bash "$test"
    done
  fi
}

# Quick lint everything
lint-all() {
  echo "🔍 Linting all code..."

  # Python
  if find . -name "*.py" | grep -q .; then
    echo "Linting Python files..."
    python3 -m flake8 . 2>/dev/null || echo "⚠️  flake8 not installed"
  fi

  # Shell
  if find . -name "*.sh" | grep -q .; then
    echo "Linting Shell scripts..."
    sh-check .
  fi
}

# Quick format everything
format-all() {
  echo "✨ Formatting all code..."

  # Python
  if find . -name "*.py" | grep -q .; then
    echo "Formatting Python files..."
    python3 -m black . 2>/dev/null || echo "⚠️  black not installed"
  fi

  # Shell
  if find . -name "*.sh" | grep -q .; then
    echo "Formatting Shell scripts..."
    sh-format .
  fi
}

EOF

  echo -e "${GREEN}✓ Aliases created: $ALIASES_FILE${RESET}"
}

# Create templates
create_templates() {
  mkdir -p "$TEMPLATES_DIR"

  # Python script template
  cat > "$TEMPLATES_DIR/python-script.py" << 'EOF'
#!/usr/bin/env python3
"""
Quick Python script template
Optimized for rapid development
"""
import sys
import os
from pathlib import Path


def main():
    """Main function"""
    print("Python script running...")

    # Your code here
    pass


if __name__ == "__main__":
    main()
EOF

  # Shell script template
  cat > "$TEMPLATES_DIR/shell-script.sh" << 'EOF'
#!/usr/bin/env bash
# Quick shell script template
# Optimized for reliability and safety

set -euo pipefail

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly RESET='\033[0m'

# Functions
log_info() {
  echo -e "${BLUE}ℹ${RESET} $*"
}

log_success() {
  echo -e "${GREEN}✓${RESET} $*"
}

log_warning() {
  echo -e "${YELLOW}⚠${RESET} $*"
}

log_error() {
  echo -e "${RED}✗${RESET} $*" >&2
}

# Main
main() {
  log_info "Script starting..."

  # Your code here

  log_success "Done"
}

main "$@"
EOF

  chmod +x "$TEMPLATES_DIR"/*.{py,sh}

  # Python+Shell hybrid template
  cat > "$TEMPLATES_DIR/hybrid-script.sh" << 'EOF'
#!/usr/bin/env bash
# Hybrid Python+Shell script
# Uses shell for orchestration, Python for heavy lifting

set -euo pipefail

# Shell part: setup and orchestration
echo "🚀 Starting hybrid workflow..."

# Check dependencies
command -v python3 >/dev/null || { echo "Python3 required"; exit 1; }

# Python part: processing
python3 << 'PYTHON'
import sys
import json

def process():
    """Python processing logic"""
    print("Python processing...")
    # Your Python code here
    return {"status": "success"}

if __name__ == "__main__":
    result = process()
    print(json.dumps(result))
PYTHON

echo "✓ Workflow complete"
EOF

  chmod +x "$TEMPLATES_DIR/hybrid-script.sh"

  echo -e "${GREEN}✓ Templates created: $TEMPLATES_DIR${RESET}"
}

# Create quick commands
create_quick_commands() {
  mkdir -p "$HOME/.claude/bin"

  # Python quick runner
  cat > "$HOME/.claude/bin/pq" << 'EOF'
#!/usr/bin/env bash
# pq - Python Quick runner
# Usage: pq "print('hello')" or pq script.py
if [[ -f "$1" ]]; then
  python3 "$@"
else
  python3 -c "$@"
fi
EOF

  # Shell quick runner
  cat > "$HOME/.claude/bin/sq" << 'EOF'
#!/usr/bin/env bash
# sq - Shell Quick runner
# Usage: sq "ls -la" or sq script.sh
if [[ -f "$1" ]]; then
  bash "$@"
else
  bash -c "$@"
fi
EOF

  chmod +x "$HOME/.claude/bin"/*

  echo -e "${GREEN}✓ Quick commands created: ~/.claude/bin/${RESET}"
}

# Install recommended tools
recommend_tools() {
  echo -e "${YELLOW}📦 Recommended Tools for Python/Shell${RESET}"
  echo ""

  cat << 'EOF'
Python Tools:
  ✓ black       - Code formatter (pip install black)
  ✓ flake8      - Linter (pip install flake8)
  ✓ mypy        - Type checker (pip install mypy)
  ✓ pytest      - Testing (pip install pytest)
  ✓ ipython     - Enhanced REPL (pip install ipython)

Shell Tools:
  ✓ shellcheck  - Script linter (brew install shellcheck)
  ✓ shfmt       - Script formatter (brew install shfmt)
  ✓ bats        - Testing framework (brew install bats-core)

Quick install:
  Python: pip install black flake8 mypy pytest ipython
  Shell:  brew install shellcheck shfmt bats-core
EOF
}

# Setup shell integration
setup_integration() {
  local shell_rc

  if [[ -f "$HOME/.zshrc" ]]; then
    shell_rc="$HOME/.zshrc"
  elif [[ -f "$HOME/.bashrc" ]]; then
    shell_rc="$HOME/.bashrc"
  else
    echo -e "${YELLOW}⚠ No shell rc file found${RESET}"
    return
  fi

  # Check if already sourced
  if grep -q "python-shell.sh" "$shell_rc"; then
    echo -e "${BLUE}ℹ Already integrated with $shell_rc${RESET}"
    return
  fi

  # Add source line
  cat >> "$shell_rc" << 'EOF'

# Python & Shell workflow optimizations (auto-added by Claude)
if [[ -f "$HOME/.claude/aliases/python-shell.sh" ]]; then
  source "$HOME/.claude/aliases/python-shell.sh"
fi

# Add Claude bin to PATH
export PATH="$HOME/.claude/bin:$PATH"
EOF

  echo -e "${GREEN}✓ Integrated with $shell_rc${RESET}"
  echo -e "${YELLOW}  Run: source $shell_rc${RESET}"
}

# Show usage
show_usage() {
  cat << 'EOF'
Python & Shell Workflow Optimizer

QUICK COMMANDS:
  pq "print('hello')"      - Quick Python execution
  sq "ls -la"              - Quick shell execution

PYTHON SHORTCUTS:
  py                       - python3
  py-test                  - Run pytest
  py-venv                  - Create & activate virtualenv
  py-check                 - Environment check
  py-deps                  - Analyze dependencies

SHELL SHORTCUTS:
  ll, la                   - Better ls
  ff <name>                - Find file
  gg <pattern>             - Grep recursively
  sh-check                 - Lint shell scripts

WORKFLOWS:
  project-init <name>      - Create Python/Shell project
  run-all-tests            - Run all tests
  lint-all                 - Lint everything
  format-all               - Format everything

TEMPLATES:
  ~/.claude/templates/python-script.py
  ~/.claude/templates/shell-script.sh
  ~/.claude/templates/hybrid-script.sh

To activate:
  source ~/.zshrc  (or ~/.bashrc)

For help:
  cat ~/.claude/aliases/python-shell.sh
EOF
}

# Main
main() {
  local command="${1:-install}"

  case "$command" in
    install)
      echo -e "${BLUE}Installing Python/Shell optimizations...${RESET}"
      echo ""
      create_aliases
      create_templates
      create_quick_commands
      setup_integration
      echo ""
      recommend_tools
      echo ""
      echo -e "${GREEN}✓ Installation complete!${RESET}"
      echo ""
      show_usage
      ;;
    uninstall)
      rm -rf "$ALIASES_FILE" "$TEMPLATES_DIR" "$HOME/.claude/bin"
      echo -e "${GREEN}✓ Uninstalled${RESET}"
      ;;
    usage|help)
      show_usage
      ;;
    *)
      echo "Unknown command: $command"
      echo "Usage: $0 [install|uninstall|usage]"
      exit 1
      ;;
  esac
}

main "$@"
